### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by pkrumins** [defunct/node-ec2#1]
Does this module still work? I am asking because I can't get it to authenticate. I am always getting:

```
{ Errors: 
   [ { Code: 'SignatureDoesNotMatch'
     , Message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'
     }
   ]
, RequestID: 'b1f6c04a-e249-4ca1-967b-bcb1915ec1e0'
}
```

Any ideas what might cause it to fail? I tried creating a new key and it still didn't work.

Here is the code that I have:

```
var ec2 = require('ec2');

var client = ec2.createClient({
    key : '... my key ...',
    secret : '... my secret ..'
});

client.call("StartInstances", { InstanceId : "i-b6ab03db" }, function (resp) {
    console.log(resp);
});

client.on("end", function () {
    console.log('end');
});

client.on("error", function (err, code) {
   console.dir(err);
   console.log(code);
   console.log('----')
```

   });

   client.poll("DescribeInstances", function (struct) {
       console.log(struct);
       return true;
   });

   client.execute();

Thank you!

**Comment by pkrumins** [comment]
Okay, I located the problem and now i am fixing it.

The trouble was that you used process.env for the secret key and not the secret key variable in the createClient constructor.

I'll send a pull request shortly!

**Comment by bigeasy** [comment]
I'm embarrassed that I ever had an example of code on the Internet with secrets in environment variables.
