### ISSUE TITLE
ec2 API wsdl 2012-10-01 has been released

### ISSUE THREAD

**Issue by glennschler** [defunct/node-ec2#32]
node-ec2 has the wsdl version hard coded to an old version when you send the query string request. Noticed when DescribeSpotInstanceRequests API Action was not returning what was documented by aws.

**Comment by bigeasy** [comment]
Will fix in the next 24 hours. Sorry.

**Comment by glennschler** [comment]
No rush. I fixed my local copy, and have no pressing need for a server
update.
Thanks.

**Comment by glennschler** [comment]
Would you like me to fix this and issue a pull request?

**Comment by bigeasy** [comment]
Yes, please.

**Comment by glennschler** [comment]
Issue resolved.
