### ISSUE TITLE
Not a string or buffer?

### ISSUE THREAD

**Issue by ghost** [defunct/node-ec2#4]
Hi,

Not sure what this error is being caused by, I run "node amazon-test.js":

``` javascript
var stack = require('../lib/long-stack-traces'); 
var ec2 = require('ec2');

var client = ec2.createClient({ 
    key: process.env['key'], 
    secret: process.env['secret']
});

client.poll("DescribeInstances", function (struct) {
    console.log(struct);
    return true;
}); 
client.execute();
```

This returns an error at line 40, which is really "client.execute()" after cleaning up some code:
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Not a string or buffer
    at Object.createHmac (crypto.js:103:21)
    at /node_modules/ec2/lib/request.js:53:19
    at AmazonEC2Client.<anonymous> (/node_modules/ec2/lib/amazon.js:53:16)
    at AmazonEC2Client.execute (/node_modules/ec2/lib/amazon.js:3:63)
    at Object.<anonymous> (amazon-test.js:40:8)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)

**Comment by bigeasy** [comment]
Note that I've changed the rest of my code to use an `~/.aws` for configuration, since using the environment to pass in the keys is insecure, but...

It looks like the secret is not set? Try setting it your environment, or finding a smarter way to feed it in. I'll update the documentation to show how to use an `~/.aws` file.

**Comment by ghost** [comment]
You know, that should have seemed apparent - but sometimes you just miss the most simple things.  Setting the environment variables did the trick.  Thanks!
