### ISSUE TITLE
Unable to trap request connection error

### ISSUE THREAD

**Issue by ghost** [defunct/node-ec2#6]
It can happen that the http request to the EC2 web service times out.  When that occurs, there is no way for the caller to trap the event.  

Specifically, I have obtained an unexpected error 10006 (timeout) several times, and this is causing the node process to crash.  Please add code to trap a request error and expose it via the existing error event.

**Comment by bigeasy** [comment]
I'm capturing said error and forwarding it through the `EventEmitter` interface. I don't have a good way to test the timeout at the moment. Please let me know if this resolves the issue for you.

**Comment by bigeasy** [comment]
New version is `0.0.9` and it is in NPM.

**Comment by ghost** [comment]
Wow, thanks for the quick response!  Testing now... (I have a long-running scenario where the timeout occurs fairly consistently)...

**Comment by ghost** [comment]
I have reviewed and the issue is not fixed.  Looking at the code, I think I see the problem.  The error occurs when the request object connects at a tcp socket level, so the catch will have to be on the request instead of the response, e.g. 

``` coffeescript
  # Connect to the Amazon Query API server, gather the response, and feed it to
  # the callback function.
  request = http.request
    port: 443
    host: "ec2.#{endpoint}.amazonaws.com"
    method: "GET"
    path: "/?" + query.join "&"
    headers: { host: "ec2.#{endpoint}.amazonaws.com" }
    (response) ->
      body = ""
      response.setEncoding "utf8"
      response.on "data", (chunk) -> body += chunk
      response.on "end", () -> callback null, response, body
      response.on "error", (error) -> callback error

  request.on "error", (error) -> callback error
  request.end()
  true
```

(3rd last line - I don't know coffeescript so hopefully the syntax is right).

**Comment by bigeasy** [comment]
Try now with version 0.0.10 on NPM. Thank you for the feedback.

**Comment by ghost** [comment]
Now ec2 is broken :( 

Should be `request` on the new line, not `response` (which is not defined at that level).

**Comment by bigeasy** [comment]
Sorry. Updated. Pull `0.0.11`.

**Comment by bigeasy** [comment]
Any luck?

**Comment by ghost** [comment]
Yes, it is fixed :)

Many thanks!
