### ISSUE TITLE
load configuration.json securely

### ISSUE THREAD

**Issue by nkhine** [defunct/node-ec2#8]
hello,
i got this to work, but have some questions.

basically, it checks if a site is running
    var http = require('http')
      , url = require('url')
      , util = require('util')
      , exec = require('child_process').exec;

```
var site = http.createClient(80, "www.domain.tld", false);
var req = site.request("GET", "/");
req.end();
req.on('response', function(res){
    if(res.statusCode !== 200){
        // launch a new instance
        var ec2 = require("ec2")
            , fs = require("fs");
        // Read in the configuration above.
        var configuration = JSON.parse(fs.readFileSync("configuration.json", "utf8"));
        // Create an ec2 function that uses your configuration.
        ec2 = ec2(configuration)
        // Run an instance and wait for it to become ready.
        ec2("RunInstances", {
            ImageId: "ami-XXXXXX"
            , KeyName: "micros-ie"
            , InstanceType: "t1.micro"
            , MinCount: 1
            , MaxCount: 1
        }, function (error, response) {
            if (error) {
                throw error
            }
        });
        } else {
            res.on('data', function(chunk){
            function puts(error, stdout, stderr) { util.puts(stdout) }
              exec("my command", puts);
            }); 
        }
});
```

basically, i want to start my first instance from my local computer and then chain the second, third ... etc so for example, when the 'site' returns a non 200 OK status code, i want to fire up a new EC2 instance, thus i don't have to have my local machine connected

is there a better way to do this?

**Comment by bigeasy** [comment]
I'm sorry. I'm not sure I understand the problem. Please help me understand.

This is what I read: When you get a response other than 200, you want to launch a new instance at Amazon.

I don't understand the requirement that your local machine is not connected. If you are running this script from your local machine, won't it have to be connected to both request `www.domain.tld` and connect to EC2?

**Comment by nkhine** [comment]
hi, i wanted to be able to create a 'chain' of t1.micro instances where the 'chain' is initialised from my local machine and any subsequent instances are initialised depending on the response of www.domain.tld from the EC2 instance rather then the local machine.

perhaps an easier way is to just use something like nodester to do the monitoring and the launching and shutting down of the EC2 instances, rather then using it from my local machine.

hope this makes sense.

thanks for any advise.

**Comment by bigeasy** [comment]
You are going to need to run `node-ec2` on the instance you launch. Do you have a plan for that?

**Comment by nkhine** [comment]
yes, i have an EC2 image which has node-ec2 running, where i manually add the configuration.json file. 

are there any secure ways to pass the configuration.json data from one instance to the next? or am i missing something?

**Comment by bigeasy** [comment]
You could pass the configuration.json in as EC2 user data. You would have to create an image that has a program that runs at startup that launches your monitoring process.

Alternatively, you can use ssh or scp once the program loads to copy the configuration.json into place and start the process remotely.

Either way, a simple bash program would be a good choice for the glue.

The `scp` way, you'd launch your other machine using a `special_key` key pair. Then you can poll `DescribeInstances` to get an idea of when the instance is ready and get its local network IP address. Then you can copy over your configuration securely with a script like this.

```
#!/bin/bash

INTERNAL_IP=$1

scp -i /var/aws/lib/special_key -o StrictHostKeyChecking=no ./configuration.json $INTERNAL_IP@/var/aws/run/configuation.json
```

I use `ssh` as my secure machine to machine protocol and glue my Node.js programs together with `bash`.

**Comment by nkhine** [comment]
ok thanks for your time and advise
