### ISSUE TITLE
Unexpected token error \u0000 when installing with npm

### ISSUE THREAD

**Issue by velniukas** [defunct/node-ec2#9]
I see this error on Lion, but it's fine on ubuntu

$ sudo npm install ec2
npm http GET https://registry.npmjs.org/ec2
npm http 304 https://registry.npmjs.org/ec2
npm http GET https://registry.npmjs.org/ec2/-/ec2-0.1.0.tgz
npm http 200 https://registry.npmjs.org/ec2/-/ec2-0.1.0.tgz
npm ERR! error reading /tmp/npm-1335796170160/1335796170160-0.39644423476420343/package
npm ERR! couldn't pack /tmp/npm-1335796170160/1335796170160-0.39644423476420343/package to /Users/auser/.npm/ec2/0.1.0/package.tgz

npm ERR! SyntaxError: Unexpected token 
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:179:33)
npm ERR!     at Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at [object Object].<anonymous> (fs.js:115:5)
npm ERR!     at [object Object].emit (events.js:64:17)
npm ERR!     at afterRead (fs.js:1117:12)
npm ERR!     at Object.wrapper [as oncomplete](fs.js:254:17)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "ec2"
npm ERR! cwd /Users/auser/dev/myapp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.18
npm ERR! file /tmp/npm-1335796170160/1335796170160-0.39644423476420343/package/.AppleDouble/package.json
npm ERR! path /tmp/npm-1335796170160/1335796170160-0.39644423476420343/package/.AppleDouble
npm ERR! type unexpected_token
npm ERR! fstream_path /tmp/npm-1335796170160/1335796170160-0.39644423476420343/package/.AppleDouble
npm ERR! fstream_type Directory
npm ERR! fstream_class Packer
npm ERR! arguments [ '\u0000' ]
npm ERR! message Unexpected token 
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:182:10)
npm ERR! fstream_stack Packer.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack [object Object].<anonymous> (fs.js:115:5)
npm ERR! fstream_stack [object Object].emit (events.js:64:17)
npm ERR! fstream_stack afterRead (fs.js:1117:12)
npm ERR! fstream_stack Object.wrapper [as oncomplete](fs.js:254:17)

**Comment by pulkitsinghal** [comment]
+1 I get the same problem:

```
$ node --version
v0.7.10-pre

$ npm --version
1.1.23

$ sudo npm install ec2
SyntaxError: Unexpected token 
npm ERR!     at Object.parse (native)
npm ERR!     at Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:179:33)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR!     at fs.readFile (fs.js:151:14)
npm ERR!     at Object.fs.close [as oncomplete] (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
...
npm ERR! arguments [ '\u0000' ]
npm ERR! message Unexpected token 
npm ERR! fstream_stack Packer.readRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/fstream-npm.js:182:10)
npm ERR! fstream_stack Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:132:22)
npm ERR! fstream_stack fs.readFile (fs.js:151:14)
npm ERR! fstream_stack Object.fs.close [as oncomplete] (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)

npm ERR! TypeError: Cannot call method 'filter' of undefined
npm ERR!     at Packer.IgnoreReader.addIgnoreRules (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:148:13)
npm ERR!     at Packer.IgnoreReader.addIgnoreFile (/usr/local/lib/node_modules/npm/node_modules/fstream-npm/node_modules/fstream-ignore/ignore.js:133:10)
npm ERR!     at fs.readFile (fs.js:151:14)
npm ERR!     at Object.fs.close [as oncomplete] (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:94:5)
```
